# Generated by Django 3.0.8 on 2020-08-17 09:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import face_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='TestVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=face_app.models.test_videos)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(blank=True, max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('regno', models.CharField(max_length=30, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('phoneNumber', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number entered was not correctly formated!!', regex='^\\+?1?\\d{10,15}$')])),
                ('image', models.ImageField(upload_to='student_pics')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='face_app.Course')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
