# Generated by Django 3.0.8 on 2020-07-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(blank=True, max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('regno', models.CharField(max_length=30, unique=True)),
                ('course', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField(max_length=20)),
                ('phoneNumber', models.PositiveIntegerField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='student_pics')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
