# Generated by Django 3.0.8 on 2020-07-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0003_auto_20200717_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='photo',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='student_pics'),
        ),
    ]
