# Generated by Django 3.0.8 on 2020-08-18 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0004_auto_20200818_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Registration Number entered was not correctly formated!!', regex='^[A-Z]{3}/[A-Z]{3}/[0-9]{2}/?[0-9]{5}$')]),
        ),
    ]
